version: '3'
services:
  frontend:
    container_name: tf-react
    build: 
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./app/frontend:/app
  
  backend:
    container_name: tf-nest
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8000:8000
    restart: always
    tty: true
    volumes:
      - ./app/backend:/app
    
  db:
    image: mariadb:latest
    container_name: tf-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tfdb
      MYSQL_USER: nest
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyoa
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306


