version: '3'
services:
  frontend:
    container_name: tf-react
    build: 
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./app/frontend:/app
  
  backend:
    container_name: tf-nest
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8000:8000
    restart: always
    tty: true
    volumes:
      - ./app/backend:/app
    
  db:
    image: postgres:latest
    container_name: tf-postgres
    volumes:
    - ./data/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest_db


